package com.even.model;

import com.even.model.base.BaseIp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ip extends BaseIp<Ip> {
	public static final Ip dao = new Ip().dao();
}
