package com.even.model;

import com.even.model.base.BaseUserMonitorTicket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMonitorTicket extends BaseUserMonitorTicket<UserMonitorTicket> {
	public static final UserMonitorTicket dao = new UserMonitorTicket().dao();
}
