package com.even.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIp<M extends BaseIp<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setPort(java.lang.Integer port) {
		set("port", port);
		return (M)this;
	}

	public java.lang.Integer getPort() {
		return getInt("port");
	}

	public M setUsable(java.lang.Boolean usable) {
		set("usable", usable);
		return (M)this;
	}

	public java.lang.Boolean getUsable() {
		return get("usable");
	}

}
