package com.even.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserMonitorTicket<M extends BaseUserMonitorTicket<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setState(java.lang.Boolean state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

	public M setTicketCount(java.lang.Integer ticketCount) {
		set("ticket_count", ticketCount);
		return (M)this;
	}

	public java.lang.Integer getTicketCount() {
		return getInt("ticket_count");
	}

	public M setDptStationName(java.lang.String dptStationName) {
		set("dpt_station_name", dptStationName);
		return (M)this;
	}

	public java.lang.String getDptStationName() {
		return getStr("dpt_station_name");
	}

	public M setArrStationName(java.lang.String arrStationName) {
		set("arr_station_name", arrStationName);
		return (M)this;
	}

	public java.lang.String getArrStationName() {
		return getStr("arr_station_name");
	}

	public M setTrainNum(java.lang.String trainNum) {
		set("train_num", trainNum);
		return (M)this;
	}

	public java.lang.String getTrainNum() {
		return getStr("train_num");
	}

	public M setStartDate(java.lang.Integer startDate) {
		set("start_date", startDate);
		return (M)this;
	}

	public java.lang.Integer getStartDate() {
		return getInt("start_date");
	}

	public M setSeats(java.lang.String seats) {
		set("seats", seats);
		return (M)this;
	}

	public java.lang.String getSeats() {
		return getStr("seats");
	}

	public M setPrice(java.lang.Float price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.Float getPrice() {
		return getFloat("price");
	}

}
